labeler:
  HEROKU_APP_NAME: damp-spire-74868 # Set to falsy to stop pings
  HEROKU_WAKEUP_FREQUENCY: 300000 # every 5 min
  ORG_WHITELIST:
    - preset-io
relay:
  WEBHOOKS:
    - https://my.webhookrelay.com/v1/webhooks/ef7bcd96-42d9-44e7-8644-4118c100eaeb